default:
  prompt: |
    Use the R language, the tidyverse, and tidymodels
  provider: LlamaGPT
  path: ~/LlamaGPTJ-chat/build/bin/chat
  label: GPT4ALL 1.3 (LlamaGPT)
  model: ~/ggml-gpt4all-j-v1.3-groovy.bin
  max_data_files: 0
  max_data_frames: 0
  include_doc_contents: FALSE
  include_history: FALSE
  model_arguments:
    threads: 4
    temp: 0.01
    n_predict: 1000
